In [4]:
import pandas as pd
pd.read_csv("../../classData.csv")

                                                                                                                              <<<<<<< HEAD
G                                                C   B   A   Ia           Ib           Ic           Va          Vb                      Vc
1                                                0   0   1   -151.2918124 -9.677451563 85.80016226  0.400749853 -0.132934945  -0.267814907
                                                             -336.1861826 -76.28326195 18.32889658  0.312731934 -0.123633156  -0.189098779
                                                             -502.891583  -174.6480233 -80.92466346 0.265728444 -0.114300749  -0.151427695
                                                             -593.9419049 -217.7033594 -124.8919239 0.235510535 -0.104940254  -0.130570281
...                                                                                                                                    ...
0                                                0   0   0   -65.84949333 37.46545409  25.51567475  0.10377809  -0.555185531   0.451407441
                                                             -65.44669763 36.4720551   26.10655368  0.11310658  -0.558210927   0.445104348
                                                             -65.02963273 35.47708841  26.68473109  0.122404174 -0.561094199   0.438690025
                                                             -64.59840133 34.48079878  27.25006492  0.131668579 -0.563834635   0.432166056
>>>>>>> 86a1d048fcc34558fa29d8ee935901de522837e9 NaN NaN NaN NaN          NaN          NaN          NaN         NaN                    NaN

[15726 rows x 1 columns]

In [3]:
x

3